# Aplicacion (Frontend, API, Celery)
# Blue/Green deployment - este compose se usa con -p ${APP_NAME}_blue o -p ${APP_NAME}_green
#
# DB y Redis estan en compose.infra.yaml (compartidos entre blue/green)
#
# Uso:
#   make deploy          # Deploy blue-green automatico
#   make deploy-setup    # Setup inicial

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_HOST: ${NEXT_PUBLIC_API_HOST}
        NEXT_PUBLIC_APP_ENV: production
    image: ${APP_NAME:-epidemiologia}-frontend:${ENV_COLOR:-prod}
    ports:
      - "127.0.0.1:${FRONTEND_PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      SECRET_KEY: ${SECRET_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${APP_NAME:-epidemiologia}-api:${ENV_COLOR:-prod}
    ports:
      - "127.0.0.1:${API_PORT:-8000}:8000"
    environment:
      ENVIRONMENT: production
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@${APP_NAME:-epidemiologia}_postgres:5432/${DB_NAME}
      REDIS_URL: redis://${APP_NAME:-epidemiologia}_redis:6379/0
      CELERY_BROKER_URL: redis://${APP_NAME:-epidemiologia}_redis:6379/0
      CELERY_RESULT_BACKEND: redis://${APP_NAME:-epidemiologia}_redis:6379/0
      SECRET_KEY: ${SECRET_KEY}
      CORS_ORIGINS: ${CORS_ORIGINS}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - uploads:/app/uploads
      - logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery_worker:
    image: ${APP_NAME:-epidemiologia}-api:${ENV_COLOR:-prod}
    environment:
      ENVIRONMENT: production
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@${APP_NAME:-epidemiologia}_postgres:5432/${DB_NAME}
      REDIS_URL: redis://${APP_NAME:-epidemiologia}_redis:6379/0
      CELERY_BROKER_URL: redis://${APP_NAME:-epidemiologia}_redis:6379/0
      CELERY_RESULT_BACKEND: redis://${APP_NAME:-epidemiologia}_redis:6379/0
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - uploads:/app/uploads
      - logs:/app/logs
    restart: unless-stopped
    command: ["celery", "-A", "app.core.celery_app:celery_app", "worker", "--loglevel=warning", "--concurrency=4", "--queues=default,file_processing,geocoding,maintenance"]

volumes:
  uploads:
  logs:

networks:
  default:
    name: ${APP_NAME:-epidemiologia}_network
    external: true
