"""
Configuración general del sistema epidemiológico.
"""

# INFORMACIÓN DEL SISTEMA
VERSION_SISTEMA = "1.0.0"
NOMBRE_SISTEMA = "Sistema de Vigilancia Epidemiológica - Chubut"

# CÓDIGOS PROVINCIALES
CODIGO_PROVINCIA_CHUBUT = 26

# AMBIENTES
AMBIENTE_DESARROLLO = "desarrollo"
AMBIENTE_PRODUCCION = "produccion"

# CONFIGURACIÓN DE PAGINACIÓN
ITEMS_POR_PAGINA_DEFAULT = 20
ITEMS_POR_PAGINA_MAXIMO = 100

# CONFIGURACIÓN DE CACHE
CACHE_TTL_SEGUNDOS = 3600  # 1 hora
CACHE_TTL_REPORTES = 86400  # 24 horas
