"""add_dashboard_charts_table

Revision ID: 10b28921b31b
Revises: 6b15e4e33fc1
Create Date: 2025-09-16 04:43:41.412810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Always import sqlmodel for SQLModel types


# revision identifiers, used by Alembic.
revision: str = '10b28921b31b'
down_revision: Union[str, Sequence[str], None] = '6b15e4e33fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_charts',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('funcion_procesamiento', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('condiciones_display', sa.JSON(), nullable=True),
    sa.Column('tipo_visualizacion', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('configuracion_chart', sa.JSON(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_charts_codigo'), 'dashboard_charts', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_charts_codigo'), table_name='dashboard_charts')
    op.drop_table('dashboard_charts')
    # ### end Alembic commands ###
