"""add period columns to boletin_instances

Revision ID: 30924f92d5e7
Revises: 71fc65dfbf1b
Create Date: 2026-02-10 10:07:37.776297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Always import sqlmodel for SQLModel types
import geoalchemy2  # Required for Geometry types


# revision identifiers, used by Alembic.
revision: str = '30924f92d5e7'
down_revision: Union[str, Sequence[str], None] = '71fc65dfbf1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boletin_instances', sa.Column('semana_epidemiologica', sa.Integer(), nullable=True))
    op.add_column('boletin_instances', sa.Column('anio_epidemiologico', sa.Integer(), nullable=True))
    op.add_column('boletin_instances', sa.Column('fecha_inicio', sa.Date(), nullable=True))
    op.add_column('boletin_instances', sa.Column('fecha_fin', sa.Date(), nullable=True))
    op.create_index(op.f('ix_boletin_instances_anio_epidemiologico'), 'boletin_instances', ['anio_epidemiologico'], unique=False)
    op.create_index(op.f('ix_boletin_instances_semana_epidemiologica'), 'boletin_instances', ['semana_epidemiologica'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boletin_instances_semana_epidemiologica'), table_name='boletin_instances')
    op.drop_index(op.f('ix_boletin_instances_anio_epidemiologico'), table_name='boletin_instances')
    op.drop_column('boletin_instances', 'fecha_fin')
    op.drop_column('boletin_instances', 'fecha_inicio')
    op.drop_column('boletin_instances', 'anio_epidemiologico')
    op.drop_column('boletin_instances', 'semana_epidemiologica')
    # ### end Alembic commands ###
