"""Add boletin tables

Revision ID: 375dc1fb8546
Revises: 40a4e08ba52c
Create Date: 2025-11-11 12:26:30.749028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Always import sqlmodel for SQLModel types
import geoalchemy2  # Required for Geometry types


# revision identifiers, used by Alembic.
revision: str = '375dc1fb8546'
down_revision: Union[str, Sequence[str], None] = '40a4e08ba52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boletin_queries',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('query_config', sa.JSON(), nullable=False),
    sa.Column('required_params', sa.JSON(), nullable=False),
    sa.Column('result_schema', sa.JSON(), nullable=True),
    sa.Column('example_response', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boletin_queries_category'), 'boletin_queries', ['category'], unique=False)
    op.create_index(op.f('ix_boletin_queries_name'), 'boletin_queries', ['name'], unique=True)
    op.create_table('boletin_templates',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('thumbnail', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('widgets', sa.JSON(), nullable=False),
    sa.Column('cover', sa.JSON(), nullable=True),
    sa.Column('global_filters', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boletin_templates_category'), 'boletin_templates', ['category'], unique=False)
    op.create_index(op.f('ix_boletin_templates_name'), 'boletin_templates', ['name'], unique=False)
    op.create_table('boletin_instances',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('template_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('pdf_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('pdf_size', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['boletin_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boletin_instances_name'), 'boletin_instances', ['name'], unique=False)
    op.create_index(op.f('ix_boletin_instances_status'), 'boletin_instances', ['status'], unique=False)
    op.create_index(op.f('ix_boletin_instances_template_id'), 'boletin_instances', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boletin_instances_template_id'), table_name='boletin_instances')
    op.drop_index(op.f('ix_boletin_instances_status'), table_name='boletin_instances')
    op.drop_index(op.f('ix_boletin_instances_name'), table_name='boletin_instances')
    op.drop_table('boletin_instances')
    op.drop_index(op.f('ix_boletin_templates_name'), table_name='boletin_templates')
    op.drop_index(op.f('ix_boletin_templates_category'), table_name='boletin_templates')
    op.drop_table('boletin_templates')
    op.drop_index(op.f('ix_boletin_queries_name'), table_name='boletin_queries')
    op.drop_index(op.f('ix_boletin_queries_category'), table_name='boletin_queries')
    op.drop_table('boletin_queries')
    # ### end Alembic commands ###
