"""remove_id_from_enfermedad_grupo_table

Revision ID: 5931d3c68907
Revises: fbe0f27a3ce9
Create Date: 2025-12-05 23:08:14.813301

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5931d3c68907"
down_revision: Union[str, Sequence[str], None] = "fbe0f27a3ce9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_enfermedad_slug"), table_name="enfermedad")
    op.create_index("ix_enfermedad_slug", "enfermedad", ["slug"], unique=False)
    op.drop_column("enfermedad_grupo", "updated_at")
    op.drop_column("enfermedad_grupo", "created_at")
    op.drop_column("enfermedad_grupo", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "enfermedad_grupo",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "enfermedad_grupo",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "enfermedad_grupo",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index("ix_enfermedad_slug", table_name="enfermedad")
    op.create_index(op.f("ix_enfermedad_slug"), "enfermedad", ["slug"], unique=True)
    # ### end Alembic commands ###
