"""remove_status_from_boletin_instances

Revision ID: b7a987ea7a11
Revises: 825deb7f4ce8
Create Date: 2025-12-04 04:40:30.726305

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7a987ea7a11'
down_revision: Union[str, Sequence[str], None] = '825deb7f4ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boletin_instances_status'), table_name='boletin_instances')
    op.drop_column('boletin_instances', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boletin_instances', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_boletin_instances_status'), 'boletin_instances', ['status'], unique=False)
    # ### end Alembic commands ###
