"""rename_ciudadano_datos_id_evento_to_id_caso

Revision ID: b967b3ace0f6
Revises: d17da35cff5f
Create Date: 2025-12-05 23:28:42.857338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Always import sqlmodel for SQLModel types
import geoalchemy2  # Required for Geometry types


# revision identifiers, used by Alembic.
revision: str = 'b967b3ace0f6'
down_revision: Union[str, Sequence[str], None] = 'd17da35cff5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ciudadano_datos', sa.Column('id_caso', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('ciudadano_datos_id_evento_fkey'), 'ciudadano_datos', type_='foreignkey')
    op.create_foreign_key(None, 'ciudadano_datos', 'caso_epidemiologico', ['id_caso'], ['id'])
    op.drop_column('ciudadano_datos', 'id_evento')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ciudadano_datos', sa.Column('id_evento', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ciudadano_datos', type_='foreignkey')
    op.create_foreign_key(op.f('ciudadano_datos_id_evento_fkey'), 'ciudadano_datos', 'caso_epidemiologico', ['id_evento'], ['id'])
    op.drop_column('ciudadano_datos', 'id_caso')
    # ### end Alembic commands ###
