"""add_unique_constraints_to_catalog_tables

Revision ID: c352319c32e0
Revises: 5f5344038a56
Create Date: 2025-11-06 21:22:30.788285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Always import sqlmodel for SQLModel types
import geoalchemy2  # Required for Geometry types


# revision identifiers, used by Alembic.
revision: str = 'c352319c32e0'
down_revision: Union[str, Sequence[str], None] = '5f5344038a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_antecedente_epidemiologico_descripcion', 'antecedente_epidemiologico', ['descripcion'])
    op.create_unique_constraint('uq_comorbilidad_descripcion', 'comorbilidad', ['descripcion'])
    op.create_unique_constraint('uq_muestra_descripcion', 'muestra', ['descripcion'])
    op.create_unique_constraint('uq_vacuna_nombre', 'vacuna', ['nombre'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vacuna_nombre', 'vacuna', type_='unique')
    op.drop_constraint('uq_muestra_descripcion', 'muestra', type_='unique')
    op.drop_constraint('uq_comorbilidad_descripcion', 'comorbilidad', type_='unique')
    op.drop_constraint('uq_antecedente_epidemiologico_descripcion', 'antecedente_epidemiologico', type_='unique')
    # ### end Alembic commands ###
