"""make_enfermedad_slug_unique

Revision ID: d17da35cff5f
Revises: 5931d3c68907
Create Date: 2025-12-05 23:10:34.912776

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d17da35cff5f"
down_revision: Union[str, Sequence[str], None] = "5931d3c68907"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_enfermedad_slug"), table_name="enfermedad")
    op.create_index(op.f("ix_enfermedad_slug"), "enfermedad", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_enfermedad_slug"), table_name="enfermedad")
    op.create_index(op.f("ix_enfermedad_slug"), "enfermedad", ["slug"], unique=False)
    # ### end Alembic commands ###
