"""Add content field to boletin_templates

Revision ID: d45f3312e884
Revises: 375dc1fb8546
Create Date: 2025-11-11 12:42:19.543428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Always import sqlmodel for SQLModel types
import geoalchemy2  # Required for Geometry types


# revision identifiers, used by Alembic.
revision: str = 'd45f3312e884'
down_revision: Union[str, Sequence[str], None] = '375dc1fb8546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boletin_templates', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boletin_templates', 'content')
    # ### end Alembic commands ###
