"""
Constantes de configuración del sistema.

Incluye configuraciones generales y parámetros del sistema.
"""

from .configuracion import (
    AMBIENTE_DESARROLLO,
    AMBIENTE_PRODUCCION,
    CACHE_TTL_REPORTES,
    CACHE_TTL_SEGUNDOS,
    CODIGO_PROVINCIA_CHUBUT,
    ITEMS_POR_PAGINA_DEFAULT,
    ITEMS_POR_PAGINA_MAXIMO,
    NOMBRE_SISTEMA,
    VERSION_SISTEMA,
)

__all__ = [
    "VERSION_SISTEMA",
    "NOMBRE_SISTEMA",
    "CODIGO_PROVINCIA_CHUBUT",
    "AMBIENTE_DESARROLLO",
    "AMBIENTE_PRODUCCION",
    "ITEMS_POR_PAGINA_DEFAULT",
    "ITEMS_POR_PAGINA_MAXIMO",
    "CACHE_TTL_SEGUNDOS",
    "CACHE_TTL_REPORTES",
]
